#!/usr/bin/env node
'use strict';

/**
 * Write scrapper-admin-ui/.env from timeline-scraper/.env (admin key + port).
 * Usage: node scripts/bootstrap-env.cjs
 */

const fs = require('node:fs');
const path = require('node:path');
const { findScrapperEnvPath } = require('./resolveTimelineScraperRoot.cjs');

const outPath = path.resolve(__dirname, '../.env');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing env file: ${filePath}`);
  }
  const map = new Map();
  for (const line of fs.readFileSync(filePath, 'utf8').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx <= 0) continue;
    const key = trimmed.slice(0, idx).trim();
    let value = trimmed.slice(idx + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"'))
      || (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    map.set(key, value);
  }
  return map;
}

function main() {
  const scrapperEnvPath = findScrapperEnvPath();
  const env = parseEnvFile(scrapperEnvPath);
  const port = env.get('TIMELINE_SCRAPPER_PORT') || '4011';
  const adminKey = env.get('SCRAPPER_ADMIN_API_KEY') || '';
  if (!adminKey) {
    throw new Error('timeline-scraper/.env has no SCRAPPER_ADMIN_API_KEY');
  }

  const lines = [
    '# Generated by scripts/bootstrap-env.cjs — do not commit',
    '# Vite dev server proxies /scrapper-api → timeline-scraper',
    'VITE_SCRAPPER_API_BASE_URL=/scrapper-api',
    `VITE_SCRAPPER_ADMIN_API_KEY=${adminKey}`,
    '',
    `# timeline-scraper listens on ${port} (proxy target in vite.config.ts)`,
  ];

  fs.writeFileSync(outPath, `${lines.join('\n')}\n`);
  console.log(`Wrote ${outPath}`);
}

main();
